/********************************************************************
* G4QTDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error G4QTDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableG4QTDict();
extern void G__cpp_setup_inheritanceG4QTDict();
extern void G__cpp_setup_typetableG4QTDict();
extern void G__cpp_setup_memvarG4QTDict();
extern void G__cpp_setup_globalG4QTDict();
extern void G__cpp_setup_memfuncG4QTDict();
extern void G__cpp_setup_funcG4QTDict();
extern void G__set_cpp_environmentG4QTDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "G4QT.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__G4QTDictLN_TClass;
extern G__linked_taginfo G__G4QTDictLN_TBuffer;
extern G__linked_taginfo G__G4QTDictLN_TMemberInspector;
extern G__linked_taginfo G__G4QTDictLN_TObject;
extern G__linked_taginfo G__G4QTDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__G4QTDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__G4QTDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__G4QTDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__G4QTDictLN_G4QT;
extern G__linked_taginfo G__G4QTDictLN_vectorlEG4QTcOallocatorlEG4QTgRsPgR;
extern G__linked_taginfo G__G4QTDictLN_vectorlEG4QTcOallocatorlEG4QTgRsPgRcLcLiterator;
extern G__linked_taginfo G__G4QTDictLN_reverse_iteratorlEvectorlEG4QTcOallocatorlEG4QTgRsPgRcLcLiteratorgR;

/* STUB derived class for protected member access */
typedef vector<G4QT,allocator<G4QT> > G__vectorlEG4QTcOallocatorlEG4QTgRsPgR;
