//
// File generated by rootcint at Thu Jun  2 10:44:31 2016

// Do NOT change. Changes will be lost next time file is generated
//

#define R__DICTIONARY_FILENAME G4QTDict
#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "G4QTDict.h"

#include "TCollectionProxyInfo.h"
#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"
#include "TFileMergeInfo.h"

// Direct notice to TROOT of the dictionary's loading.
namespace {
   static struct DictInit {
      DictInit() {
         ROOT::RegisterModule();
      }
   } __TheDictionaryInitializer;
}

// START OF SHADOWS

namespace ROOT {
   namespace Shadow {
   } // of namespace Shadow
} // of namespace ROOT
// END OF SHADOWS

namespace ROOT {
   void G4QT_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void *new_G4QT(void *p = 0);
   static void *newArray_G4QT(Long_t size, void *p);
   static void delete_G4QT(void *p);
   static void deleteArray_G4QT(void *p);
   static void destruct_G4QT(void *p);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const ::G4QT*)
   {
      ::G4QT *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::G4QT >(0);
      static ::ROOT::TGenericClassInfo 
         instance("G4QT", ::G4QT::Class_Version(), "./G4QT.h", 7,
                  typeid(::G4QT), DefineBehavior(ptr, ptr),
                  &::G4QT::Dictionary, isa_proxy, 4,
                  sizeof(::G4QT) );
      instance.SetNew(&new_G4QT);
      instance.SetNewArray(&newArray_G4QT);
      instance.SetDelete(&delete_G4QT);
      instance.SetDeleteArray(&deleteArray_G4QT);
      instance.SetDestructor(&destruct_G4QT);
      return &instance;
   }
   TGenericClassInfo *GenerateInitInstance(const ::G4QT*)
   {
      return GenerateInitInstanceLocal((::G4QT*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::G4QT*)0x0); R__UseDummy(_R__UNIQUE_(Init));
} // end of namespace ROOT

//______________________________________________________________________________
TClass *G4QT::fgIsA = 0;  // static to hold class pointer

//______________________________________________________________________________
const char *G4QT::Class_Name()
{
   return "G4QT";
}

//______________________________________________________________________________
const char *G4QT::ImplFileName()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::G4QT*)0x0)->GetImplFileName();
}

//______________________________________________________________________________
int G4QT::ImplFileLine()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::G4QT*)0x0)->GetImplFileLine();
}

//______________________________________________________________________________
void G4QT::Dictionary()
{
   fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::G4QT*)0x0)->GetClass();
}

//______________________________________________________________________________
TClass *G4QT::Class()
{
   if (!fgIsA) fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::G4QT*)0x0)->GetClass();
   return fgIsA;
}

//______________________________________________________________________________
void G4QT::Streamer(TBuffer &R__b)
{
   // Stream an object of class G4QT.

   if (R__b.IsReading()) {
      R__b.ReadClassBuffer(G4QT::Class(),this);
   } else {
      R__b.WriteClassBuffer(G4QT::Class(),this);
   }
}

//______________________________________________________________________________
void G4QT::ShowMembers(TMemberInspector &R__insp)
{
      // Inspect the data members of an object of class G4QT.
      TClass *R__cl = ::G4QT::IsA();
      if (R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__insp.GetParent(), "n_primaries", &n_primaries);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "nStored", &nStored);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "event", &event);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "nQTdata", &nQTdata);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "QTdata[3700]", QTdata);
      TObject::ShowMembers(R__insp);
}

namespace ROOT {
   // Wrappers around operator new
   static void *new_G4QT(void *p) {
      return  p ? new(p) ::G4QT : new ::G4QT;
   }
   static void *newArray_G4QT(Long_t nElements, void *p) {
      return p ? new(p) ::G4QT[nElements] : new ::G4QT[nElements];
   }
   // Wrapper around operator delete
   static void delete_G4QT(void *p) {
      delete ((::G4QT*)p);
   }
   static void deleteArray_G4QT(void *p) {
      delete [] ((::G4QT*)p);
   }
   static void destruct_G4QT(void *p) {
      typedef ::G4QT current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOT for class ::G4QT

namespace ROOT {
   void vectorlEG4QTgR_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void vectorlEG4QTgR_Dictionary();
   static void *new_vectorlEG4QTgR(void *p = 0);
   static void *newArray_vectorlEG4QTgR(Long_t size, void *p);
   static void delete_vectorlEG4QTgR(void *p);
   static void deleteArray_vectorlEG4QTgR(void *p);
   static void destruct_vectorlEG4QTgR(void *p);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const vector<G4QT>*)
   {
      vector<G4QT> *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(vector<G4QT>),0);
      static ::ROOT::TGenericClassInfo 
         instance("vector<G4QT>", -2, "prec_stl/vector", 49,
                  typeid(vector<G4QT>), DefineBehavior(ptr, ptr),
                  0, &vectorlEG4QTgR_Dictionary, isa_proxy, 4,
                  sizeof(vector<G4QT>) );
      instance.SetNew(&new_vectorlEG4QTgR);
      instance.SetNewArray(&newArray_vectorlEG4QTgR);
      instance.SetDelete(&delete_vectorlEG4QTgR);
      instance.SetDeleteArray(&deleteArray_vectorlEG4QTgR);
      instance.SetDestructor(&destruct_vectorlEG4QTgR);
      instance.AdoptCollectionProxyInfo(TCollectionProxyInfo::Generate(TCollectionProxyInfo::Pushback< vector<G4QT> >()));
      return &instance;
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const vector<G4QT>*)0x0); R__UseDummy(_R__UNIQUE_(Init));

   // Dictionary for non-ClassDef classes
   static void vectorlEG4QTgR_Dictionary() {
      ::ROOT::GenerateInitInstanceLocal((const vector<G4QT>*)0x0)->GetClass();
   }

} // end of namespace ROOT

namespace ROOT {
   // Wrappers around operator new
   static void *new_vectorlEG4QTgR(void *p) {
      return  p ? ::new((::ROOT::TOperatorNewHelper*)p) vector<G4QT> : new vector<G4QT>;
   }
   static void *newArray_vectorlEG4QTgR(Long_t nElements, void *p) {
      return p ? ::new((::ROOT::TOperatorNewHelper*)p) vector<G4QT>[nElements] : new vector<G4QT>[nElements];
   }
   // Wrapper around operator delete
   static void delete_vectorlEG4QTgR(void *p) {
      delete ((vector<G4QT>*)p);
   }
   static void deleteArray_vectorlEG4QTgR(void *p) {
      delete [] ((vector<G4QT>*)p);
   }
   static void destruct_vectorlEG4QTgR(void *p) {
      typedef vector<G4QT> current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOT for class vector<G4QT>

/********************************************************
* G4QTDict.cxx
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && __GNUC__ >= 4 && ((__GNUC_MINOR__ == 2 && __GNUC_PATCHLEVEL__ >= 1) || (__GNUC_MINOR__ >= 3))
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtableG4QTDict();

extern "C" void G__set_cpp_environmentG4QTDict() {
  G__add_compiledheader("TObject.h");
  G__add_compiledheader("TMemberInspector.h");
  G__add_compiledheader("G4QT.h");
  G__cpp_reset_tagtableG4QTDict();
}
#include <new>
extern "C" int G__cpp_dllrevG4QTDict() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* G4QT */
static int G__G4QTDict_168_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   G4QT* p = NULL;
   char* gvp = (char*) G__getgvp();
   int n = G__getaryconstruct();
   if (n) {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new G4QT[n];
     } else {
       p = new((void*) gvp) G4QT[n];
     }
   } else {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new G4QT;
     } else {
       p = new((void*) gvp) G4QT;
     }
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__G4QTDictLN_G4QT));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G4QTDict_168_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((G4QT*) G__getstructoffset())->SetNPrimaries((UInt_t) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G4QTDict_168_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((G4QT*) G__getstructoffset())->SetEvent((UInt_t) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G4QTDict_168_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((G4QT*) G__getstructoffset())->SetNQTdata((UInt_t) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G4QTDict_168_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((G4QT*) G__getstructoffset())->FillQT((UInt_t*) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G4QTDict_168_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((G4QT*) G__getstructoffset())->SetNStored((UInt_t) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G4QTDict_168_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 104, (long) ((G4QT*) G__getstructoffset())->GetNPrimaries());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G4QTDict_168_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 104, (long) ((G4QT*) G__getstructoffset())->GetEvent());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G4QTDict_168_0_9(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 104, (long) ((G4QT*) G__getstructoffset())->GetNQTdata());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G4QTDict_168_0_10(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 72, (long) ((G4QT*) G__getstructoffset())->GetQT());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G4QTDict_168_0_11(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) G4QT::Class());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G4QTDict_168_0_12(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) G4QT::Class_Name());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G4QTDict_168_0_13(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 115, (long) G4QT::Class_Version());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G4QTDict_168_0_14(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G4QT::Dictionary();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G4QTDict_168_0_18(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((G4QT*) G__getstructoffset())->StreamerNVirtual(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G4QTDict_168_0_19(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) G4QT::DeclFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G4QTDict_168_0_20(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) G4QT::ImplFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G4QTDict_168_0_21(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) G4QT::ImplFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G4QTDict_168_0_22(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) G4QT::DeclFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__G4QTDict_168_0_23(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)

{
   G4QT* p;
   void* tmp = (void*) G__int(libp->para[0]);
   p = new G4QT(*(G4QT*) tmp);
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__G4QTDictLN_G4QT));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef G4QT G__TG4QT;
static int G__G4QTDict_168_0_24(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 1
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (G4QT*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((G4QT*) (soff+(sizeof(G4QT)*i)))->~G__TG4QT();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (G4QT*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((G4QT*) (soff))->~G__TG4QT();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic assignment operator
static int G__G4QTDict_168_0_25(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   G4QT* dest = (G4QT*) G__getstructoffset();
   *dest = *(G4QT*) libp->para[0].ref;
   const G4QT& obj = *dest;
   result7->ref = (long) (&obj);
   result7->obj.i = (long) (&obj);
   return(1 || funcname || hash || result7 || libp) ;
}


/* vector<G4QT,allocator<G4QT> > */
static int G__G4QTDict_170_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         const vector<G4QT,allocator<G4QT> >::reference obj = ((vector<G4QT,allocator<G4QT> >*) G__getstructoffset())->at((vector<G4QT,allocator<G4QT> >::size_type) G__int(libp->para[0]));
         result7->ref = (long) (&obj);
         result7->obj.i = (long) (&obj);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G4QTDict_170_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         vector<G4QT,allocator<G4QT> >::const_reference obj = ((const vector<G4QT,allocator<G4QT> >*) G__getstructoffset())->at((vector<G4QT,allocator<G4QT> >::size_type) G__int(libp->para[0]));
         result7->ref = (long) (&obj);
         result7->obj.i = (long) (&obj);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G4QTDict_170_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         vector<G4QT,allocator<G4QT> >::iterator* pobj;
         vector<G4QT,allocator<G4QT> >::iterator xobj = ((vector<G4QT,allocator<G4QT> >*) G__getstructoffset())->begin();
         pobj = new vector<G4QT,allocator<G4QT> >::iterator(xobj);
         result7->obj.i = (long) ((void*) pobj);
         result7->ref = result7->obj.i;
         G__store_tempobject(*result7);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G4QTDict_170_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         vector<G4QT,allocator<G4QT> >::iterator* pobj;
         vector<G4QT,allocator<G4QT> >::iterator xobj = ((vector<G4QT,allocator<G4QT> >*) G__getstructoffset())->end();
         pobj = new vector<G4QT,allocator<G4QT> >::iterator(xobj);
         result7->obj.i = (long) ((void*) pobj);
         result7->ref = result7->obj.i;
         G__store_tempobject(*result7);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G4QTDict_170_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         vector<G4QT,allocator<G4QT> >::reverse_iterator* pobj;
         vector<G4QT,allocator<G4QT> >::reverse_iterator xobj = ((vector<G4QT,allocator<G4QT> >*) G__getstructoffset())->rbegin();
         pobj = new vector<G4QT,allocator<G4QT> >::reverse_iterator(xobj);
         result7->obj.i = (long) ((void*) pobj);
         result7->ref = result7->obj.i;
         G__store_tempobject(*result7);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G4QTDict_170_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         vector<G4QT,allocator<G4QT> >::reverse_iterator* pobj;
         vector<G4QT,allocator<G4QT> >::reverse_iterator xobj = ((vector<G4QT,allocator<G4QT> >*) G__getstructoffset())->rend();
         pobj = new vector<G4QT,allocator<G4QT> >::reverse_iterator(xobj);
         result7->obj.i = (long) ((void*) pobj);
         result7->ref = result7->obj.i;
         G__store_tempobject(*result7);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G4QTDict_170_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 107, (long) ((const vector<G4QT,allocator<G4QT> >*) G__getstructoffset())->size());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G4QTDict_170_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 107, (long) ((const vector<G4QT,allocator<G4QT> >*) G__getstructoffset())->max_size());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G4QTDict_170_0_9(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((vector<G4QT,allocator<G4QT> >*) G__getstructoffset())->resize((vector<G4QT,allocator<G4QT> >::size_type) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G4QTDict_170_0_10(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((vector<G4QT,allocator<G4QT> >*) G__getstructoffset())->resize((vector<G4QT,allocator<G4QT> >::size_type) G__int(libp->para[0]), *((G4QT*) G__int(libp->para[1])));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G4QTDict_170_0_11(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 107, (long) ((const vector<G4QT,allocator<G4QT> >*) G__getstructoffset())->capacity());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G4QTDict_170_0_12(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) ((const vector<G4QT,allocator<G4QT> >*) G__getstructoffset())->empty());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G4QTDict_170_0_13(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         const vector<G4QT,allocator<G4QT> >::reference obj = ((vector<G4QT,allocator<G4QT> >*) G__getstructoffset())->operator[]((vector<G4QT,allocator<G4QT> >::size_type) G__int(libp->para[0]));
         result7->ref = (long) (&obj);
         result7->obj.i = (long) (&obj);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G4QTDict_170_0_14(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         vector<G4QT,allocator<G4QT> >::const_reference obj = ((const vector<G4QT,allocator<G4QT> >*) G__getstructoffset())->operator[]((vector<G4QT,allocator<G4QT> >::size_type) G__int(libp->para[0]));
         result7->ref = (long) (&obj);
         result7->obj.i = (long) (&obj);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G4QTDict_170_0_15(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   vector<G4QT,allocator<G4QT> >* p = NULL;
   char* gvp = (char*) G__getgvp();
   int n = G__getaryconstruct();
   if (n) {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new vector<G4QT,allocator<G4QT> >[n];
     } else {
       p = new((void*) gvp) vector<G4QT,allocator<G4QT> >[n];
     }
   } else {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new vector<G4QT,allocator<G4QT> >;
     } else {
       p = new((void*) gvp) vector<G4QT,allocator<G4QT> >;
     }
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__G4QTDictLN_vectorlEG4QTcOallocatorlEG4QTgRsPgR));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G4QTDict_170_0_16(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   vector<G4QT,allocator<G4QT> >* p = NULL;
   char* gvp = (char*) G__getgvp();
   switch (libp->paran) {
   case 2:
     //m: 2
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new vector<G4QT,allocator<G4QT> >((vector<G4QT,allocator<G4QT> >::size_type) G__int(libp->para[0]), *(G4QT*) libp->para[1].ref);
     } else {
       p = new((void*) gvp) vector<G4QT,allocator<G4QT> >((vector<G4QT,allocator<G4QT> >::size_type) G__int(libp->para[0]), *(G4QT*) libp->para[1].ref);
     }
     break;
   case 1:
     //m: 1
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new vector<G4QT,allocator<G4QT> >((vector<G4QT,allocator<G4QT> >::size_type) G__int(libp->para[0]));
     } else {
       p = new((void*) gvp) vector<G4QT,allocator<G4QT> >((vector<G4QT,allocator<G4QT> >::size_type) G__int(libp->para[0]));
     }
     break;
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__G4QTDictLN_vectorlEG4QTcOallocatorlEG4QTgRsPgR));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G4QTDict_170_0_17(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   vector<G4QT,allocator<G4QT> >* p = NULL;
   char* gvp = (char*) G__getgvp();
   //m: 1
   if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
     p = new vector<G4QT,allocator<G4QT> >(*(vector<G4QT,allocator<G4QT> >*) libp->para[0].ref);
   } else {
     p = new((void*) gvp) vector<G4QT,allocator<G4QT> >(*(vector<G4QT,allocator<G4QT> >*) libp->para[0].ref);
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__G4QTDictLN_vectorlEG4QTcOallocatorlEG4QTgRsPgR));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G4QTDict_170_0_18(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   vector<G4QT,allocator<G4QT> >* p = NULL;
   char* gvp = (char*) G__getgvp();
   //m: 2
   if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
     p = new vector<G4QT,allocator<G4QT> >(*((vector<G4QT,allocator<G4QT> >::const_iterator*) G__int(libp->para[0])), *((vector<G4QT,allocator<G4QT> >::const_iterator*) G__int(libp->para[1])));
   } else {
     p = new((void*) gvp) vector<G4QT,allocator<G4QT> >(*((vector<G4QT,allocator<G4QT> >::const_iterator*) G__int(libp->para[0])), *((vector<G4QT,allocator<G4QT> >::const_iterator*) G__int(libp->para[1])));
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__G4QTDictLN_vectorlEG4QTcOallocatorlEG4QTgRsPgR));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G4QTDict_170_0_19(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         const vector<G4QT,allocator<G4QT> >& obj = ((vector<G4QT,allocator<G4QT> >*) G__getstructoffset())->operator=(*(vector<G4QT,allocator<G4QT> >*) libp->para[0].ref);
         result7->ref = (long) (&obj);
         result7->obj.i = (long) (&obj);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G4QTDict_170_0_20(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((vector<G4QT,allocator<G4QT> >*) G__getstructoffset())->reserve((vector<G4QT,allocator<G4QT> >::size_type) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G4QTDict_170_0_21(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         const G4QT& obj = ((vector<G4QT,allocator<G4QT> >*) G__getstructoffset())->front();
         result7->ref = (long) (&obj);
         result7->obj.i = (long) (&obj);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G4QTDict_170_0_22(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         const G4QT& obj = ((vector<G4QT,allocator<G4QT> >*) G__getstructoffset())->back();
         result7->ref = (long) (&obj);
         result7->obj.i = (long) (&obj);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G4QTDict_170_0_23(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((vector<G4QT,allocator<G4QT> >*) G__getstructoffset())->push_back(*(G4QT*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G4QTDict_170_0_24(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((vector<G4QT,allocator<G4QT> >*) G__getstructoffset())->swap(*(vector<G4QT,allocator<G4QT> >*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G4QTDict_170_0_25(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         vector<G4QT,allocator<G4QT> >::iterator* pobj;
         vector<G4QT,allocator<G4QT> >::iterator xobj = ((vector<G4QT,allocator<G4QT> >*) G__getstructoffset())->insert(*((vector<G4QT,allocator<G4QT> >::iterator*) G__int(libp->para[0])), *(G4QT*) libp->para[1].ref);
         pobj = new vector<G4QT,allocator<G4QT> >::iterator(xobj);
         result7->obj.i = (long) ((void*) pobj);
         result7->ref = result7->obj.i;
         G__store_tempobject(*result7);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G4QTDict_170_0_26(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((vector<G4QT,allocator<G4QT> >*) G__getstructoffset())->insert(*((vector<G4QT,allocator<G4QT> >::iterator*) G__int(libp->para[0])), *((vector<G4QT,allocator<G4QT> >::const_iterator*) G__int(libp->para[1]))
, *((vector<G4QT,allocator<G4QT> >::const_iterator*) G__int(libp->para[2])));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G4QTDict_170_0_27(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((vector<G4QT,allocator<G4QT> >*) G__getstructoffset())->insert(*((vector<G4QT,allocator<G4QT> >::iterator*) G__int(libp->para[0])), (vector<G4QT,allocator<G4QT> >::size_type) G__int(libp->para[1])
, *(G4QT*) libp->para[2].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G4QTDict_170_0_28(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((vector<G4QT,allocator<G4QT> >*) G__getstructoffset())->pop_back();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G4QTDict_170_0_29(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((vector<G4QT,allocator<G4QT> >*) G__getstructoffset())->erase(*((vector<G4QT,allocator<G4QT> >::iterator*) G__int(libp->para[0])));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G4QTDict_170_0_30(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((vector<G4QT,allocator<G4QT> >*) G__getstructoffset())->erase(*((vector<G4QT,allocator<G4QT> >::iterator*) G__int(libp->para[0])), *((vector<G4QT,allocator<G4QT> >::iterator*) G__int(libp->para[1])));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G4QTDict_170_0_31(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((vector<G4QT,allocator<G4QT> >*) G__getstructoffset())->clear();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef vector<G4QT,allocator<G4QT> > G__TvectorlEG4QTcOallocatorlEG4QTgRsPgR;
static int G__G4QTDict_170_0_32(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 0
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (vector<G4QT,allocator<G4QT> >*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((vector<G4QT,allocator<G4QT> >*) (soff+(sizeof(vector<G4QT,allocator<G4QT> >)*i)))->~G__TvectorlEG4QTcOallocatorlEG4QTgRsPgR();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (vector<G4QT,allocator<G4QT> >*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((vector<G4QT,allocator<G4QT> >*) (soff))->~G__TvectorlEG4QTcOallocatorlEG4QTgRsPgR();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* G4QT */

/* vector<G4QT,allocator<G4QT> > */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncG4QTDict {
 public:
  G__Sizep2memfuncG4QTDict(): p(&G__Sizep2memfuncG4QTDict::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncG4QTDict::*p)();
};

size_t G__get_sizep2memfuncG4QTDict()
{
  G__Sizep2memfuncG4QTDict a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritanceG4QTDict() {

   /* Setting up class inheritance */
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__G4QTDictLN_G4QT))) {
     G4QT *G__Lderived;
     G__Lderived=(G4QT*)0x1000;
     {
       TObject *G__Lpbase=(TObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__G4QTDictLN_G4QT),G__get_linked_tagnum(&G__G4QTDictLN_TObject),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
   }
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetableG4QTDict() {

   /* Setting up typedef entry */
   G__search_typename2("UInt_t",104,-1,0,-1);
   G__setnewtype(-1,"Unsigned integer 4 bytes (unsigned int)",0);
   G__search_typename2("Version_t",115,-1,0,-1);
   G__setnewtype(-1,"Class version identifier (short)",0);
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__G4QTDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__G4QTDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__G4QTDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__G4QTDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__G4QTDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVirtualArray*>",117,G__get_linked_tagnum(&G__G4QTDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__G4QTDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__G4QTDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__G4QTDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__G4QTDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<G4QT>",117,G__get_linked_tagnum(&G__G4QTDictLN_vectorlEG4QTcOallocatorlEG4QTgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("value_type",117,G__get_linked_tagnum(&G__G4QTDictLN_G4QT),0,G__get_linked_tagnum(&G__G4QTDictLN_vectorlEG4QTcOallocatorlEG4QTgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("pointer",85,G__get_linked_tagnum(&G__G4QTDictLN_G4QT),0,G__get_linked_tagnum(&G__G4QTDictLN_vectorlEG4QTcOallocatorlEG4QTgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("const_pointer",85,G__get_linked_tagnum(&G__G4QTDictLN_G4QT),256,G__get_linked_tagnum(&G__G4QTDictLN_vectorlEG4QTcOallocatorlEG4QTgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reference",117,G__get_linked_tagnum(&G__G4QTDictLN_G4QT),1,G__get_linked_tagnum(&G__G4QTDictLN_vectorlEG4QTcOallocatorlEG4QTgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("const_reference",117,G__get_linked_tagnum(&G__G4QTDictLN_G4QT),257,G__get_linked_tagnum(&G__G4QTDictLN_vectorlEG4QTcOallocatorlEG4QTgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("size_type",107,-1,0,G__get_linked_tagnum(&G__G4QTDictLN_vectorlEG4QTcOallocatorlEG4QTgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("difference_type",108,-1,0,G__get_linked_tagnum(&G__G4QTDictLN_vectorlEG4QTcOallocatorlEG4QTgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("const_iterator",117,G__get_linked_tagnum(&G__G4QTDictLN_vectorlEG4QTcOallocatorlEG4QTgRsPgRcLcLiterator),256,G__get_linked_tagnum(&G__G4QTDictLN_vectorlEG4QTcOallocatorlEG4QTgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__G4QTDictLN_reverse_iteratorlEvectorlEG4QTcOallocatorlEG4QTgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__G4QTDictLN_vectorlEG4QTcOallocatorlEG4QTgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("const_reverse_iterator",117,G__get_linked_tagnum(&G__G4QTDictLN_reverse_iteratorlEvectorlEG4QTcOallocatorlEG4QTgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__G4QTDictLN_vectorlEG4QTcOallocatorlEG4QTgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__G4QTDictLN_reverse_iteratorlEvectorlEG4QTcOallocatorlEG4QTgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__G4QTDictLN_vectorlEG4QTcOallocatorlEG4QTgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator",117,G__get_linked_tagnum(&G__G4QTDictLN_reverse_iteratorlEvectorlEG4QTcOallocatorlEG4QTgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__G4QTDictLN_vectorlEG4QTcOallocatorlEG4QTgRsPgR));
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* G4QT */
static void G__setup_memvarG4QT(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__G4QTDictLN_G4QT));
   { G4QT *p; p=(G4QT*)0x1000; if (p) { }
   G__memvar_setup((void*)((long)(&p->n_primaries)-(long)(p)),104,0,0,-1,G__defined_typename("UInt_t"),-1,1,"n_primaries=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->nStored)-(long)(p)),104,0,0,-1,G__defined_typename("UInt_t"),-1,1,"nStored=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->event)-(long)(p)),104,0,0,-1,G__defined_typename("UInt_t"),-1,1,"event=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->nQTdata)-(long)(p)),104,0,0,-1,G__defined_typename("UInt_t"),-1,1,"nQTdata=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->QTdata)-(long)(p)),104,0,0,-1,G__defined_typename("UInt_t"),-1,1,"QTdata[3700]=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__G4QTDictLN_TClass),-1,-2,4,"fgIsA=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}


   /* vector<G4QT,allocator<G4QT> > */
static void G__setup_memvarvectorlEG4QTcOallocatorlEG4QTgRsPgR(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__G4QTDictLN_vectorlEG4QTcOallocatorlEG4QTgRsPgR));
   { vector<G4QT,allocator<G4QT> > *p; p=(vector<G4QT,allocator<G4QT> >*)0x1000; if (p) { }
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarG4QTDict() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncG4QT(void) {
   /* G4QT */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__G4QTDictLN_G4QT));
   G__memfunc_setup("G4QT",288,G__G4QTDict_168_0_1, 105, G__get_linked_tagnum(&G__G4QTDictLN_G4QT), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetNPrimaries",1318,G__G4QTDict_168_0_2, 121, -1, -1, 0, 1, 1, 1, 0, "h - 'UInt_t' 0 - n", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetEvent",814,G__G4QTDict_168_0_3, 121, -1, -1, 0, 1, 1, 1, 0, "h - 'UInt_t' 0 - ev", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetNQTdata",953,G__G4QTDict_168_0_4, 121, -1, -1, 0, 1, 1, 1, 0, "h - 'UInt_t' 0 - nqt", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("FillQT",556,G__G4QTDict_168_0_5, 121, -1, -1, 0, 1, 1, 1, 0, "H - 'UInt_t' 0 - QT_", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetNStored",1003,G__G4QTDict_168_0_6, 121, -1, -1, 0, 1, 1, 1, 0, "h - 'UInt_t' 0 - nstor", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetNPrimaries",1306,G__G4QTDict_168_0_7, 104, -1, G__defined_typename("UInt_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetEvent",802,G__G4QTDict_168_0_8, 104, -1, G__defined_typename("UInt_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetNQTdata",941,G__G4QTDict_168_0_9, 104, -1, G__defined_typename("UInt_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetQT",453,G__G4QTDict_168_0_10, 72, -1, G__defined_typename("UInt_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Class",502,G__G4QTDict_168_0_11, 85, G__get_linked_tagnum(&G__G4QTDictLN_TClass), -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (TClass* (*)())(&G4QT::Class) ), 0);
   G__memfunc_setup("Class_Name",982,G__G4QTDict_168_0_12, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&G4QT::Class_Name) ), 0);
   G__memfunc_setup("Class_Version",1339,G__G4QTDict_168_0_13, 115, -1, G__defined_typename("Version_t"), 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (Version_t (*)())(&G4QT::Class_Version) ), 0);
   G__memfunc_setup("Dictionary",1046,G__G4QTDict_168_0_14, 121, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (void (*)())(&G4QT::Dictionary) ), 0);
   G__memfunc_setup("IsA",253,(G__InterfaceMethod) NULL,85, G__get_linked_tagnum(&G__G4QTDictLN_TClass), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ShowMembers",1132,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TMemberInspector' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Streamer",835,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("StreamerNVirtual",1656,G__G4QTDict_168_0_18, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - ClassDef_StreamerNVirtual_b", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DeclFileName",1145,G__G4QTDict_168_0_19, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&G4QT::DeclFileName) ), 0);
   G__memfunc_setup("ImplFileLine",1178,G__G4QTDict_168_0_20, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&G4QT::ImplFileLine) ), 0);
   G__memfunc_setup("ImplFileName",1171,G__G4QTDict_168_0_21, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&G4QT::ImplFileName) ), 0);
   G__memfunc_setup("DeclFileLine",1152,G__G4QTDict_168_0_22, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&G4QT::DeclFileLine) ), 0);
   // automatic copy constructor
   G__memfunc_setup("G4QT", 288, G__G4QTDict_168_0_23, (int) ('i'), G__get_linked_tagnum(&G__G4QTDictLN_G4QT), -1, 0, 1, 1, 1, 0, "u 'G4QT' - 11 - -", (char*) NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~G4QT", 414, G__G4QTDict_168_0_24, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   // automatic assignment operator
   G__memfunc_setup("operator=", 937, G__G4QTDict_168_0_25, (int) ('u'), G__get_linked_tagnum(&G__G4QTDictLN_G4QT), -1, 1, 1, 1, 1, 0, "u 'G4QT' - 11 - -", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}

static void G__setup_memfuncvectorlEG4QTcOallocatorlEG4QTgRsPgR(void) {
   /* vector<G4QT,allocator<G4QT> > */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__G4QTDictLN_vectorlEG4QTcOallocatorlEG4QTgRsPgR));
   G__memfunc_setup("at",213,G__G4QTDict_170_0_1, 117, G__get_linked_tagnum(&G__G4QTDictLN_G4QT), G__defined_typename("vector<G4QT,allocator<G4QT> >::reference"), 1, 1, 1, 1, 0, "k - 'vector<G4QT,allocator<G4QT> >::size_type' 0 - n", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("at",213,G__G4QTDict_170_0_2, 117, G__get_linked_tagnum(&G__G4QTDictLN_G4QT), G__defined_typename("vector<G4QT,allocator<G4QT> >::const_reference"), 1, 1, 1, 1, 8, "k - 'vector<G4QT,allocator<G4QT> >::size_type' 0 - n", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("begin",517,G__G4QTDict_170_0_3, 117, G__get_linked_tagnum(&G__G4QTDictLN_vectorlEG4QTcOallocatorlEG4QTgRsPgRcLcLiterator), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("end",311,G__G4QTDict_170_0_4, 117, G__get_linked_tagnum(&G__G4QTDictLN_vectorlEG4QTcOallocatorlEG4QTgRsPgRcLcLiterator), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("rbegin",631,G__G4QTDict_170_0_5, 117, G__get_linked_tagnum(&G__G4QTDictLN_reverse_iteratorlEvectorlEG4QTcOallocatorlEG4QTgRsPgRcLcLiteratorgR), G__defined_typename("vector<G4QT,allocator<G4QT> >::reverse_iterator"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("rend",425,G__G4QTDict_170_0_6, 117, G__get_linked_tagnum(&G__G4QTDictLN_reverse_iteratorlEvectorlEG4QTcOallocatorlEG4QTgRsPgRcLcLiteratorgR), G__defined_typename("vector<G4QT,allocator<G4QT> >::reverse_iterator"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("size",443,G__G4QTDict_170_0_7, 107, -1, G__defined_typename("vector<G4QT,allocator<G4QT> >::size_type"), 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("max_size",864,G__G4QTDict_170_0_8, 107, -1, G__defined_typename("vector<G4QT,allocator<G4QT> >::size_type"), 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("resize",658,G__G4QTDict_170_0_9, 121, -1, -1, 0, 1, 1, 1, 0, "k - 'vector<G4QT,allocator<G4QT> >::size_type' 0 - sz", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("resize",658,G__G4QTDict_170_0_10, 121, -1, -1, 0, 2, 1, 1, 0, 
"k - 'vector<G4QT,allocator<G4QT> >::size_type' 0 - sz u 'G4QT' - 0 - c", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("capacity",846,G__G4QTDict_170_0_11, 107, -1, G__defined_typename("vector<G4QT,allocator<G4QT> >::size_type"), 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("empty",559,G__G4QTDict_170_0_12, 103, -1, -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("operator[]",1060,G__G4QTDict_170_0_13, 117, G__get_linked_tagnum(&G__G4QTDictLN_G4QT), G__defined_typename("vector<G4QT,allocator<G4QT> >::reference"), 1, 1, 1, 1, 0, "k - 'vector<G4QT,allocator<G4QT> >::size_type' 0 - n", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("operator[]",1060,G__G4QTDict_170_0_14, 117, G__get_linked_tagnum(&G__G4QTDictLN_G4QT), G__defined_typename("vector<G4QT,allocator<G4QT> >::const_reference"), 1, 1, 1, 1, 8, "k - 'vector<G4QT,allocator<G4QT> >::size_type' 0 - n", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("vector<G4QT,allocator<G4QT> >",2516,G__G4QTDict_170_0_15, 105, G__get_linked_tagnum(&G__G4QTDictLN_vectorlEG4QTcOallocatorlEG4QTgRsPgR), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("vector<G4QT,allocator<G4QT> >",2516,G__G4QTDict_170_0_16, 105, G__get_linked_tagnum(&G__G4QTDictLN_vectorlEG4QTcOallocatorlEG4QTgRsPgR), -1, 0, 2, 1, 1, 0, 
"k - 'vector<G4QT,allocator<G4QT> >::size_type' 0 - n u 'G4QT' - 11 'G4QT()' value", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("vector<G4QT,allocator<G4QT> >",2516,G__G4QTDict_170_0_17, 105, G__get_linked_tagnum(&G__G4QTDictLN_vectorlEG4QTcOallocatorlEG4QTgRsPgR), -1, 0, 1, 1, 1, 0, "u 'vector<G4QT,allocator<G4QT> >' - 11 - x", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("vector<G4QT,allocator<G4QT> >",2516,G__G4QTDict_170_0_18, 105, G__get_linked_tagnum(&G__G4QTDictLN_vectorlEG4QTcOallocatorlEG4QTgRsPgR), -1, 0, 2, 1, 1, 0, 
"u 'vector<G4QT,allocator<G4QT> >::iterator' 'vector<G4QT,allocator<G4QT> >::const_iterator' 10 - first u 'vector<G4QT,allocator<G4QT> >::iterator' 'vector<G4QT,allocator<G4QT> >::const_iterator' 10 - last", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("operator=",937,G__G4QTDict_170_0_19, 117, G__get_linked_tagnum(&G__G4QTDictLN_vectorlEG4QTcOallocatorlEG4QTgRsPgR), -1, 1, 1, 1, 1, 0, "u 'vector<G4QT,allocator<G4QT> >' - 11 - x", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("reserve",764,G__G4QTDict_170_0_20, 121, -1, -1, 0, 1, 1, 1, 0, "k - 'vector<G4QT,allocator<G4QT> >::size_type' 0 - n", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("front",553,G__G4QTDict_170_0_21, 117, G__get_linked_tagnum(&G__G4QTDictLN_G4QT), -1, 1, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("back",401,G__G4QTDict_170_0_22, 117, G__get_linked_tagnum(&G__G4QTDictLN_G4QT), -1, 1, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("push_back",944,G__G4QTDict_170_0_23, 121, -1, -1, 0, 1, 1, 1, 0, "u 'G4QT' - 11 - x", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("swap",443,G__G4QTDict_170_0_24, 121, -1, -1, 0, 1, 1, 1, 0, "u 'vector<G4QT,allocator<G4QT> >' - 1 - x", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("insert",661,G__G4QTDict_170_0_25, 117, G__get_linked_tagnum(&G__G4QTDictLN_vectorlEG4QTcOallocatorlEG4QTgRsPgRcLcLiterator), -1, 0, 2, 1, 1, 0, 
"u 'vector<G4QT,allocator<G4QT> >::iterator' - 0 - position u 'G4QT' - 11 - x", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("insert",661,G__G4QTDict_170_0_26, 121, -1, -1, 0, 3, 1, 1, 0, 
"u 'vector<G4QT,allocator<G4QT> >::iterator' - 0 - position u 'vector<G4QT,allocator<G4QT> >::iterator' 'vector<G4QT,allocator<G4QT> >::const_iterator' 10 - first "
"u 'vector<G4QT,allocator<G4QT> >::iterator' 'vector<G4QT,allocator<G4QT> >::const_iterator' 10 - last", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("insert",661,G__G4QTDict_170_0_27, 121, -1, -1, 0, 3, 1, 1, 0, 
"u 'vector<G4QT,allocator<G4QT> >::iterator' - 0 - position k - 'vector<G4QT,allocator<G4QT> >::size_type' 0 - n "
"u 'G4QT' - 11 - x", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("pop_back",831,G__G4QTDict_170_0_28, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("erase",528,G__G4QTDict_170_0_29, 121, -1, -1, 0, 1, 1, 1, 0, "u 'vector<G4QT,allocator<G4QT> >::iterator' - 0 - position", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("erase",528,G__G4QTDict_170_0_30, 121, -1, -1, 0, 2, 1, 1, 0, 
"u 'vector<G4QT,allocator<G4QT> >::iterator' - 0 - first u 'vector<G4QT,allocator<G4QT> >::iterator' - 0 - last", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("clear",519,G__G4QTDict_170_0_31, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~vector<G4QT,allocator<G4QT> >", 2642, G__G4QTDict_170_0_32, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncG4QTDict() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalG4QTDict() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {
}

static void G__cpp_setup_func12() {
}

static void G__cpp_setup_func13() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcG4QTDict() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
  G__cpp_setup_func12();
  G__cpp_setup_func13();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__G4QTDictLN_TClass = { "TClass" , 99 , -1 };
G__linked_taginfo G__G4QTDictLN_TBuffer = { "TBuffer" , 99 , -1 };
G__linked_taginfo G__G4QTDictLN_TMemberInspector = { "TMemberInspector" , 99 , -1 };
G__linked_taginfo G__G4QTDictLN_TObject = { "TObject" , 99 , -1 };
G__linked_taginfo G__G4QTDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__G4QTDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__G4QTDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR = { "vector<TVirtualArray*,allocator<TVirtualArray*> >" , 99 , -1 };
G__linked_taginfo G__G4QTDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__G4QTDictLN_G4QT = { "G4QT" , 99 , -1 };
G__linked_taginfo G__G4QTDictLN_vectorlEG4QTcOallocatorlEG4QTgRsPgR = { "vector<G4QT,allocator<G4QT> >" , 99 , -1 };
G__linked_taginfo G__G4QTDictLN_vectorlEG4QTcOallocatorlEG4QTgRsPgRcLcLiterator = { "vector<G4QT,allocator<G4QT> >::iterator" , 99 , -1 };
G__linked_taginfo G__G4QTDictLN_reverse_iteratorlEvectorlEG4QTcOallocatorlEG4QTgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<G4QT,allocator<G4QT> >::iterator>" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtableG4QTDict() {
  G__G4QTDictLN_TClass.tagnum = -1 ;
  G__G4QTDictLN_TBuffer.tagnum = -1 ;
  G__G4QTDictLN_TMemberInspector.tagnum = -1 ;
  G__G4QTDictLN_TObject.tagnum = -1 ;
  G__G4QTDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__G4QTDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__G4QTDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR.tagnum = -1 ;
  G__G4QTDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__G4QTDictLN_G4QT.tagnum = -1 ;
  G__G4QTDictLN_vectorlEG4QTcOallocatorlEG4QTgRsPgR.tagnum = -1 ;
  G__G4QTDictLN_vectorlEG4QTcOallocatorlEG4QTgRsPgRcLcLiterator.tagnum = -1 ;
  G__G4QTDictLN_reverse_iteratorlEvectorlEG4QTcOallocatorlEG4QTgRsPgRcLcLiteratorgR.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtableG4QTDict() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__G4QTDictLN_TClass);
   G__get_linked_tagnum_fwd(&G__G4QTDictLN_TBuffer);
   G__get_linked_tagnum_fwd(&G__G4QTDictLN_TMemberInspector);
   G__get_linked_tagnum_fwd(&G__G4QTDictLN_TObject);
   G__get_linked_tagnum_fwd(&G__G4QTDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__G4QTDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__G4QTDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR);
   G__get_linked_tagnum_fwd(&G__G4QTDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__G4QTDictLN_G4QT),sizeof(G4QT),-1,292096,(char*)NULL,G__setup_memvarG4QT,G__setup_memfuncG4QT);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__G4QTDictLN_vectorlEG4QTcOallocatorlEG4QTgRsPgR),sizeof(vector<G4QT,allocator<G4QT> >),-1,298752,(char*)NULL,G__setup_memvarvectorlEG4QTcOallocatorlEG4QTgRsPgR,G__setup_memfuncvectorlEG4QTcOallocatorlEG4QTgRsPgR);
   G__get_linked_tagnum_fwd(&G__G4QTDictLN_vectorlEG4QTcOallocatorlEG4QTgRsPgRcLcLiterator);
   G__get_linked_tagnum_fwd(&G__G4QTDictLN_reverse_iteratorlEvectorlEG4QTcOallocatorlEG4QTgRsPgRcLcLiteratorgR);
}
extern "C" void G__cpp_setupG4QTDict(void) {
  G__check_setup_version(30051515,"G__cpp_setupG4QTDict()");
  G__set_cpp_environmentG4QTDict();
  G__cpp_setup_tagtableG4QTDict();

  G__cpp_setup_inheritanceG4QTDict();

  G__cpp_setup_typetableG4QTDict();

  G__cpp_setup_memvarG4QTDict();

  G__cpp_setup_memfuncG4QTDict();
  G__cpp_setup_globalG4QTDict();
  G__cpp_setup_funcG4QTDict();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncG4QTDict();
  return;
}
class G__cpp_setup_initG4QTDict {
  public:
    G__cpp_setup_initG4QTDict() { G__add_setup_func("G4QTDict",(G__incsetup)(&G__cpp_setupG4QTDict)); G__call_setup_funcs(); }
   ~G__cpp_setup_initG4QTDict() { G__remove_setup_func("G4QTDict"); }
};
G__cpp_setup_initG4QTDict G__cpp_setup_initializerG4QTDict;

